# Default application configuration that all configurations inherit from.

scss_files: "scss/base.scss"
plugin_directories: [".scss-linters"]

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

# Default severity of all linters.
severity: warning

linters:
  NestingDepth:
    enabled: false
    max_depth: 3
    ignore_parent_selectors: false

  ImportantRule:
    enabled: false
  StringQuotes:
    enabled: true
    style: double_quotes
  ColorVariable:
    enabled: false
